// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZMMWGBOiIXBAf24s9q6LejtFKn-tOkP4',
    appId: '1:727478519938:web:1c9b2979e41a3dee52cc9b',
    messagingSenderId: '727478519938',
    projectId: 'pemob2026',
    authDomain: 'pemob2026.firebaseapp.com',
    storageBucket: 'pemob2026.firebasestorage.app',
    measurementId: 'G-NBLV7ZTPQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOMBU9qYED7491qQbGLJnDeof5vHhYTs',
    appId: '1:727478519938:android:cee194052c0da3c152cc9b',
    messagingSenderId: '727478519938',
    projectId: 'pemob2026',
    storageBucket: 'pemob2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV5ANgAGhQ2bQLrY-A5sYPlSW6AiCHqRY',
    appId: '1:727478519938:ios:8b9c95b6b944606152cc9b',
    messagingSenderId: '727478519938',
    projectId: 'pemob2026',
    storageBucket: 'pemob2026.firebasestorage.app',
    iosBundleId: 'com.example.alatMusik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV5ANgAGhQ2bQLrY-A5sYPlSW6AiCHqRY',
    appId: '1:727478519938:ios:8b9c95b6b944606152cc9b',
    messagingSenderId: '727478519938',
    projectId: 'pemob2026',
    storageBucket: 'pemob2026.firebasestorage.app',
    iosBundleId: 'com.example.alatMusik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZMMWGBOiIXBAf24s9q6LejtFKn-tOkP4',
    appId: '1:727478519938:web:bbe87045473a1e1152cc9b',
    messagingSenderId: '727478519938',
    projectId: 'pemob2026',
    authDomain: 'pemob2026.firebaseapp.com',
    storageBucket: 'pemob2026.firebasestorage.app',
    measurementId: 'G-EP46BCF2E9',
  );
}
